### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^(. ?)(?:\/(?:src|test\/unit)\/)(. ?)(?:\.js|\...

### ISSUE THREAD

**Issue by ProLoser** [vanossj/tab-pair-header-source#3]
While typing in a new regex string for advanced mode, the editor will throw an error if the Regex is invalid. I don't know how much control you have over the settings UI but it would be nice if you could catch the error and instead make the input text red or something and show a message below saying that the regex is invalid until it becomes valid again.

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [tab-pair-header-source](https://github.com/vanossj/tab-pair-header-source) package, v0.3.0
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /^(. ?)(?:\/(?:src|test\/unit)\/)(. ?)(?:.js|.spec.jsa\/: \ at end of pattern

```
At /Users/dsofer/.atom/packages/tab-pair-header-source/lib/tab-pair-header-source.js:91

SyntaxError: Invalid regular expression: /^(. ?)(?:\/(?:src|test\/unit)\/)(. ?)(?:\.js|\.spec\.jsa\/: \ at end of pattern
    at RegExp (native)
    at Object.updateConfig (/Users/dsofer/.atom/packages/tab-pair-header-source/lib/tab-pair-header-source.js:91:31)
    at /Users/dsofer/.atom/packages/tab-pair-header-source/lib/tab-pair-header-source.js:57:86
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:618:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:827:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:254:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25
```
### Commands

```
  2x -3:33 core:backspace (atom-text-editor#tab-pair-header-source.advancedMode.matchRegExp.editor.mini.is-focused)
  2x -1:14.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:42.3.0 core:backspace (atom-text-editor#tab-pair-header-source.advancedMode.matchRegExp.editor.mini.is-focused)
```

**Comment by vanossj** [comment]
Input box goes red if regex is invalid.
